### ISSUE TITLE
Server error 500 (`all_csets` / SSL error)

### ISSUE THREAD

**Issue by joeflack4** [jhu-bids/TermHub#349]
## Overview
Hey @Sigfried , Harold encountered an error this morning, he said:

> TermHub, prod and dev, give me "AxiosError: Request failed with status code 500"

I took a look and here is the error I found in [the logs](https://termhub-dev.scm.azurewebsites.net/api/vfs/LogFiles/2023_05_30_pl0mdlwk0004D5_default_docker.log):

`sqlalchemy.exc.OperationalError: (psycopg2.OperationalError) SSL connection has been closed unexpectedly`

<details><summary>Stack trace</summary>
<p>

```
2023-05-30T15:28:36.129786839Z ERROR:    Exception in ASGI application
2023-05-30T15:28:36.129830040Z Traceback (most recent call last):
2023-05-30T15:28:36.129852940Z   File "/tmp/8db588246a920ba/antenv/lib/python3.9/site-packages/sqlalchemy/engine/base.py", line 1900, in _execute_context
2023-05-30T15:28:36.129859940Z     self.dialect.do_execute(
2023-05-30T15:28:36.129865141Z   File "/tmp/8db588246a920ba/antenv/lib/python3.9/site-packages/sqlalchemy/engine/default.py", line 736, in do_execute
2023-05-30T15:28:36.129870441Z     cursor.execute(statement, parameters)
2023-05-30T15:28:36.129875541Z psycopg2.OperationalError: SSL connection has been closed unexpectedly
2023-05-30T15:28:36.129880941Z 
2023-05-30T15:28:36.129886041Z 
2023-05-30T15:28:36.129891541Z The above exception was the direct cause of the following exception:
2023-05-30T15:28:36.129896841Z 
2023-05-30T15:28:36.129901941Z Traceback (most recent call last):
2023-05-30T15:28:36.129907241Z   File "/tmp/8db588246a920ba/backend/db/utils.py", line 119, in sql_query
2023-05-30T15:28:36.129912541Z     q = con.execute(query)
2023-05-30T15:28:36.129917541Z   File "/tmp/8db588246a920ba/antenv/lib/python3.9/site-packages/sqlalchemy/engine/base.py", line 1365, in execute
2023-05-30T15:28:36.129922741Z     return self._exec_driver_sql(
2023-05-30T15:28:36.129928041Z   File "/tmp/8db588246a920ba/antenv/lib/python3.9/site-packages/sqlalchemy/engine/base.py", line 1669, in _exec_driver_sql
2023-05-30T15:28:36.129933641Z     ret = self._execute_context(
2023-05-30T15:28:36.129938641Z   File "/tmp/8db588246a920ba/antenv/lib/python3.9/site-packages/sqlalchemy/engine/base.py", line 1943, in _execute_context
2023-05-30T15:28:36.129943842Z     self._handle_dbapi_exception(
2023-05-30T15:28:36.129962542Z   File "/tmp/8db588246a920ba/antenv/lib/python3.9/site-packages/sqlalchemy/engine/base.py", line 2124, in _handle_dbapi_exception
2023-05-30T15:28:36.129967442Z     util.raise_(
2023-05-30T15:28:36.129972042Z   File "/tmp/8db588246a920ba/antenv/lib/python3.9/site-packages/sqlalchemy/util/compat.py", line 208, in raise_
2023-05-30T15:28:36.129976742Z     raise exception
2023-05-30T15:28:36.129981242Z   File "/tmp/8db588246a920ba/antenv/lib/python3.9/site-packages/sqlalchemy/engine/base.py", line 1900, in _execute_context
2023-05-30T15:28:36.129986142Z     self.dialect.do_execute(
2023-05-30T15:28:36.129990742Z   File "/tmp/8db588246a920ba/antenv/lib/python3.9/site-packages/sqlalchemy/engine/default.py", line 736, in do_execute
2023-05-30T15:28:36.129995542Z     cursor.execute(statement, parameters)
2023-05-30T15:28:36.130000042Z sqlalchemy.exc.OperationalError: (psycopg2.OperationalError) SSL connection has been closed unexpectedly
2023-05-30T15:28:36.130004742Z 
2023-05-30T15:28:36.130009242Z [SQL:  
2023-05-30T15:28:36.130013742Z         SELECT codeset_id,
2023-05-30T15:28:36.130018143Z               --concept_set_version_title,
2023-05-30T15:28:36.130022743Z               alias,
2023-05-30T15:28:36.130032443Z               version,
2023-05-30T15:28:36.130037643Z               --concepts
2023-05-30T15:28:36.130042143Z               counts
2023-05-30T15:28:36.130046643Z         FROM n3c.all_csets]
2023-05-30T15:28:36.130052643Z (Background on this error at: https://sqlalche.me/e/14/e3q8)
```

</p>
</details> 

I see that it's erroring [here](https://github.com/jhu-bids/TermHub/blame/develop/backend/app.py#L332).

I assume that the `--` is just to comment out those lines and that this is not causing the error. I see this was added 3 weeks ago and I think we would have noticed sooner if this was the cause.

Since it says SSL, maybe this indicates just a general internet connection issue. I wonder if it was a blip in Azure? I'm not experiencing any such issue when using TermHub right now.

**Comment by joeflack4** [comment]
@hlehmann17 I was able to use TermHub normally on my end. Has the issue gone away for you as well? Anything else you can elaborate with?

**Comment by hlehmann17** [comment]
Yup, works now, and displays single concept sets and is lickety fast. I am a happy camper.

**Comment by joeflack4** [comment]
Good to hear! Looks like an Azure outage, then. Hopefully that is rare.
