### ISSUE TITLE
`initialize.py` errors out before running completely. 

### ISSUE THREAD

**Issue by hugwuoke** [jhu-bids/TermHub#430]
### To Reproduce
Run `python backend/db/initalize.py`

<details><summary>Full stacktrace</summary>

```
/Users/chrisvisitor/TermHub/venv/bin/python3 /Applications/PyCharm.app/Contents/plugins/python/helpers/pydev/pydevd.py --multiprocess --qt-support=auto --client 127.0.0.1 --port 56570 --file /Users/chrisvisitor/TermHub/backend/db/initialize.py 
Connected to pydev debugger (build 231.9011.38)
INFO: Skipping upload of table "code_sets" because it is up to date.
INFO: Skipping upload of table "concept" because it is up to date.
INFO: n3c.concept_ancestor exists with 21,221,989 rows; leaving it
INFO: n3c.concept_relationship exists with 18,534,492 rows; leaving it
INFO: Skipping upload of table "concept_set_container" because it is up to date.
INFO: n3c.concept_set_counts_clamped exists with 5,084 rows; leaving it
INFO: Skipping upload of table "concept_set_members" because it is up to date.
INFO: Skipping upload of table "concept_set_version_item" because it is up to date.
INFO: n3c.deidentified_term_usage_by_domain_clamped exists with 183,386 rows; leaving it
INFO: n3c.researcher exists with 1,000 rows; leaving it
INFO: n3c.omopconceptset exists with 5,155 rows; leaving it
INFO: n3c.omopconceptsetcontainer exists with 3,968 rows; leaving it
INFO: Creating derived tables (e.g. `all_csets`) and indexes.
INFO: Creating derived tables (e.g. `all_csets`) and indexes.
INFO: Last successful command was 44 of 66. Continuing from there.
INFO: indexes_and_derived_tables: Running command 45 of 66
Traceback (most recent call last):
  File "/Users/chrisvisitor/TermHub/venv/lib/python3.10/site-packages/sqlalchemy/engine/base.py", line 1968, in _exec_single_context
    self.dialect.do_execute(
  File "/Users/chrisvisitor/TermHub/venv/lib/python3.10/site-packages/sqlalchemy/engine/default.py", line 920, in do_execute
    cursor.execute(statement, parameters)
psycopg2.errors.DependentObjectsStillExist: cannot drop table all_csets because other objects depend on it
DETAIL:  view csets_to_ignore depends on table all_csets
HINT:  Use DROP ... CASCADE to drop the dependent objects too.
The above exception was the direct cause of the following exception:
Traceback (most recent call last):
  File "/Users/chrisvisitor/TermHub/backend/db/initialize.py", line 76, in initialize
    indexes_and_derived_tables(con, schema, local=local)  # , start_step=30)
  File "/Users/chrisvisitor/TermHub/backend/db/load.py", line 176, in indexes_and_derived_tables
    raise err
  File "/Users/chrisvisitor/TermHub/backend/db/load.py", line 172, in indexes_and_derived_tables
    run_sql(con, statement)
  File "/Users/chrisvisitor/TermHub/backend/db/utils.py", line 328, in run_sql
    q = con.execute(command)
  File "/Users/chrisvisitor/TermHub/venv/lib/python3.10/site-packages/sqlalchemy/engine/base.py", line 1413, in execute
    return meth(
  File "/Users/chrisvisitor/TermHub/venv/lib/python3.10/site-packages/sqlalchemy/sql/elements.py", line 483, in _execute_on_connection
    return connection._execute_clauseelement(
  File "/Users/chrisvisitor/TermHub/venv/lib/python3.10/site-packages/sqlalchemy/engine/base.py", line 1637, in _execute_clauseelement
    ret = self._execute_context(
  File "/Users/chrisvisitor/TermHub/venv/lib/python3.10/site-packages/sqlalchemy/engine/base.py", line 1846, in _execute_context
    return self._exec_single_context(
  File "/Users/chrisvisitor/TermHub/venv/lib/python3.10/site-packages/sqlalchemy/engine/base.py", line 1987, in _exec_single_context
    self._handle_dbapi_exception(
  File "/Users/chrisvisitor/TermHub/venv/lib/python3.10/site-packages/sqlalchemy/engine/base.py", line 2344, in _handle_dbapi_exception
    raise sqlalchemy_exception.with_traceback(exc_info[2]) from e
  File "/Users/chrisvisitor/TermHub/venv/lib/python3.10/site-packages/sqlalchemy/engine/base.py", line 1968, in _exec_single_context
    self.dialect.do_execute(
  File "/Users/chrisvisitor/TermHub/venv/lib/python3.10/site-packages/sqlalchemy/engine/default.py", line 920, in do_execute
    cursor.execute(statement, parameters)
sqlalchemy.exc.InternalError: (psycopg2.errors.DependentObjectsStillExist) cannot drop table all_csets because other objects depend on it
DETAIL:  view csets_to_ignore depends on table all_csets
HINT:  Use DROP ... CASCADE to drop the dependent objects too.
[SQL: -- Table: all_csets ----------------------------------------------------------------------------------------------------
DROP TABLE IF EXISTS n3c.all_csets;]
(Background on this error at: https://sqlalche.me/e/20/2j85)
python-BaseException

```

</details> 

I will say it seems to randomly gets further sometimes, it stoped at 11 once then it stoped at 45 the next time it ran, but it stayed at 45 the third time. Also I couldn't figure out how it gave the INFO updates, I didn't see any print statements so I was curious where it was coming from?

**Comment by joeflack4** [comment]
@hugwuoke You found out how to put the stacktrace inside of the `<details>` block! Cool! Did you try the `/` command? Like you can type a `/` when you're writing a comment in GitHub and a menu will come up; that's something they added a few months ago.

The cause of the error, or the error itself, appears near the end of the stacktrace:
```
sqlalchemy.exc.InternalError: (psycopg2.errors.DependentObjectsStillExist) cannot drop table all_csets because other objects depend on it
DETAIL:  view csets_to_ignore depends on table all_csets
```

Basically when dropping a table, if there is a view that depends on it, the drop will fail unless you do `DROP CASCADE` instead of just `DROP`. I think these other views are new, which is why this is failing now.

I'm actually surprised that it did not error consistently at the same location. It may perhaps be that the first time you ran it was before my bugfix, where instead of it reading from your local database's `manage` table, it was reading from the production database's, and thusly started out on the wrong step. But other than that I'm not sure what would be the cause.

In any case this should be a simple fix! I'll try to work on it soon.

**Comment by hugwuoke** [comment]
Thank you for fixing this so quickly ! Unfortunately it still isn't running all the way. 

<details><summary>Full stacktrace</summary>

```
INFO: n3c.code_sets exists with 6,731 rows; leaving it
INFO: n3c.concept exists with 6,902,538 rows; leaving it
INFO: n3c.concept_ancestor exists with 21,221,989 rows; leaving it
INFO: n3c.concept_relationship exists with 18,534,492 rows; leaving it
INFO: n3c.concept_set_container exists with 4,462 rows; leaving it
INFO: n3c.concept_set_counts_clamped exists with 5,084 rows; leaving it
INFO: n3c.concept_set_members exists with 7,824,575 rows; leaving it
INFO: n3c.concept_set_version_item exists with 1,727,025 rows; leaving it
INFO: n3c.deidentified_term_usage_by_domain_clamped exists with 183,386 rows; leaving it
INFO: n3c.researcher exists with 1,000 rows; leaving it
INFO: n3c.omopconceptset exists with 5,155 rows; leaving it
INFO: n3c.omopconceptsetcontainer exists with 3,968 rows; leaving it
INFO: Creating derived tables (e.g. `all_csets`) and indexes.
INFO: Creating derived tables (e.g. `all_csets`) and indexes.
INFO: Last successful command was 63 of 75. Continuing from there.
INFO: indexes_and_derived_tables: Running SQL commands (75 steps total).
 - Module 1 of 17: column_types (1 commands)
  - completed in 0 seconds
 - Module 2 of 17: primary_keys (2 commands)
  - completed in 0 seconds
 - Module 3 of 17: concept_set_members (6 commands)
  - completed in 0 seconds
 - Module 4 of 17: indexes (19 commands)
  - completed in 0 seconds
 - Module 5 of 17: concept_set_container (1 commands)
  - completed in 0 seconds
 - Module 6 of 17: cset_members_items (5 commands)
  - completed in 0 seconds
 - Module 7 of 17: concept_ids_by_codeset_id (3 commands)
  - completed in 0 seconds
 - Module 8 of 17: codeset_ids_by_concept_id (3 commands)
  - completed in 0 seconds
 - Module 9 of 17: members_items_summary (3 commands)
  - completed in 0 seconds
 - Module 10 of 17: codeset_counts (3 commands)
  - completed in 0 seconds
 - Module 11 of 17: all_csets (4 commands)
  - completed in 0 seconds
 - Module 12 of 17: csets_to_ignore (1 commands)
  - completed in 0 seconds
 - Module 13 of 17: cset_members_items_plus (1 commands)
  - completed in 0 seconds
 - Module 14 of 17: concept_relationship_plus (7 commands)
  - completed in 0 seconds
 - Module 15 of 17: concepts_with_counts_ungrouped (3 commands)
  - completed in 0 seconds
 - Module 16 of 17: concepts_with_counts (4 commands)
  - 2 (step 64)
  - 3 (step 65)
Traceback (most recent call last):
  File "/Users/chrisvisitor/TermHub/venv/lib/python3.10/site-packages/sqlalchemy/engine/base.py", line 1968, in _exec_single_context
    self.dialect.do_execute(
  File "/Users/chrisvisitor/TermHub/venv/lib/python3.10/site-packages/sqlalchemy/engine/default.py", line 920, in do_execute
    cursor.execute(statement, parameters)
psycopg2.errors.DuplicateTable: relation "cc_idx1" already exists


The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/Users/chrisvisitor/TermHub/backend/db/initialize.py", line 114, in <module>
    cli()
  File "/Users/chrisvisitor/TermHub/backend/db/initialize.py", line 110, in cli
    initialize(**vars(parser.parse_args()))
  File "/Users/chrisvisitor/TermHub/backend/db/initialize.py", line 76, in initialize
    indexes_and_derived_tables(con, schema, local=local)  # , start_step=30)
  File "/Users/chrisvisitor/TermHub/backend/db/load.py", line 188, in indexes_and_derived_tables
    raise err
  File "/Users/chrisvisitor/TermHub/backend/db/load.py", line 184, in indexes_and_derived_tables
    run_sql(con, statement)
  File "/Users/chrisvisitor/TermHub/backend/db/utils.py", line 328, in run_sql
    q = con.execute(command)
  File "/Users/chrisvisitor/TermHub/venv/lib/python3.10/site-packages/sqlalchemy/engine/base.py", line 1413, in execute
    return meth(
  File "/Users/chrisvisitor/TermHub/venv/lib/python3.10/site-packages/sqlalchemy/sql/elements.py", line 483, in _execute_on_connection
    return connection._execute_clauseelement(
  File "/Users/chrisvisitor/TermHub/venv/lib/python3.10/site-packages/sqlalchemy/engine/base.py", line 1637, in _execute_clauseelement
    ret = self._execute_context(
  File "/Users/chrisvisitor/TermHub/venv/lib/python3.10/site-packages/sqlalchemy/engine/base.py", line 1846, in _execute_context
    return self._exec_single_context(
  File "/Users/chrisvisitor/TermHub/venv/lib/python3.10/site-packages/sqlalchemy/engine/base.py", line 1987, in _exec_single_context
    self._handle_dbapi_exception(
  File "/Users/chrisvisitor/TermHub/venv/lib/python3.10/site-packages/sqlalchemy/engine/base.py", line 2344, in _handle_dbapi_exception
    raise sqlalchemy_exception.with_traceback(exc_info[2]) from e
  File "/Users/chrisvisitor/TermHub/venv/lib/python3.10/site-packages/sqlalchemy/engine/base.py", line 1968, in _exec_single_context
    self.dialect.do_execute(
  File "/Users/chrisvisitor/TermHub/venv/lib/python3.10/site-packages/sqlalchemy/engine/default.py", line 920, in do_execute
    cursor.execute(statement, parameters)
sqlalchemy.exc.ProgrammingError: (psycopg2.errors.DuplicateTable) relation "cc_idx1" already exists

[SQL: CREATE INDEX cc_idx1 ON n3c.concepts_with_counts(concept_id);]
(Background on this error at: https://sqlalche.me/e/20/f405)

```

</details>

**Comment by joeflack4** [comment]
@hugwuoke I think Siggie might have fixed the issue yesterday. Did they talk to you about it? I saw on teams they mentioned that there was an issue with the first line of the DDL files not being read.

Just some advice that if you program enough, you'll start to develop like a kind of programmer "spidey sense" warning you about stuff, or you see some code that is like a "code smell", they call it. I should have listened to my spidey sense and not done this refactor on Friday which printed out better progress updates, because that is the change that ended up breaking this for you. I'm so sorry. 

Let me know if you still are getting stuck here, following Siggie's fix!

**Comment by hugwuoke** [comment]
I am still getting stuck here :( I'll talk with Siggie about it and keep you updated.
