### ISSUE TITLE
Bug: Cset comparison sometimes won't load

### ISSUE THREAD

**Issue by joeflack4** [jhu-bids/TermHub#490]
### Overview
Stephanie was trying to use this on TermHub dev (#489): https://icy-ground-0416a040f.2.azurestaticapps.net/OMOPConceptSets?codeset_ids=417730759&codeset_ids=423850600&codeset_ids=966671711&codeset_ids=577774492 but experienced some issues.

After loading csets using the URL above, she clicked "cset comparison", but it would not load.

I tried to replicate. I loaded the above URL, which took 1-2 minutes. Then I clicked "cset comparison" and it loaded after 2-3 minutes.

However, I went to do that a second time and it failed. This time, I started off in the "cset search" page, selected all of the same concept sets. Then clicked "cset comparison", and after about 10 minutes it still hasn't loaded, and there are some errors in the frontend logs, so I think it failed.

<details><summary>Frontend logs</summary>
<p>

```
16:57:04.013 Refused to load the font '<URL>' because it violates the following Content Security Policy directive: "default-src https: 'unsafe-eval' 'unsafe-inline'". Note that 'font-src' was not explicitly set, so 'default-src' is used as a fallback.

16:57:04.013 Refused to load the font '<URL>' because it violates the following Content Security Policy directive: "default-src https: 'unsafe-eval' 'unsafe-inline'". Note that 'font-src' was not explicitly set, so 'default-src' is used as a fallback.

16:57:04.013 Refused to load the font '<URL>' because it violates the following Content Security Policy directive: "default-src https: 'unsafe-eval' 'unsafe-inline'". Note that 'font-src' was not explicitly set, so 'default-src' is used as a fallback.

16:57:04.013 Refused to load the font '<URL>' because it violates the following Content Security Policy directive: "default-src https: 'unsafe-eval' 'unsafe-inline'". Note that 'font-src' was not explicitly set, so 'default-src' is used as a fallback.

16:57:04.013 Refused to load the font '<URL>' because it violates the following Content Security Policy directive: "default-src https: 'unsafe-eval' 'unsafe-inline'". Note that 'font-src' was not explicitly set, so 'default-src' is used as a fallback.

16:55:45.177 pace.min.js:6 A soft navigation has been detected: https://icy-ground-0416a040f.2.azurestaticapps.net/OMOPConceptSets?codeset_ids=423850600&codeset_ids=127148362&codeset_ids=264370170&codeset_ids=417730759
16:55:45.198 DataGetter.js:67 undefined Object
16:55:45.227 content.dd261dc5.js:1 Uncaught (in promise) TypeError: P.unmount is not a function
    at O (content.dd261dc5.js:1:320337)
    at K (content.dd261dc5.js:1:325123)
    at MutationObserver.observe.childList (content.dd261dc5.js:1:325905)
16:55:57.964 DataCache.js:96 compressed cache just grew by 100.03% to 2,320,854 chars
16:56:30.738 pace.min.js:6 A soft navigation has been detected: https://icy-ground-0416a040f.2.azurestaticapps.net/cset-comparison?codeset_ids=423850600&codeset_ids=127148362&codeset_ids=264370170&codeset_ids=417730759
16:56:30.763 DataGetter.js:67 undefined Object
16:56:30.764 DataGetter.js:67 undefined Object
16:56:30.774 DataGetter.js:67 undefined Object
16:56:30.781 content.dd261dc5.js:1 Uncaught (in promise) TypeError: P.unmount is not a function
    at O (content.dd261dc5.js:1:320337)
    at K (content.dd261dc5.js:1:325123)
    at MutationObserver.observe.childList (content.dd261dc5.js:1:325905)
16:56:32.353 DataGetter.js:67 undefined Object
16:56:32.477 CsetComparisonPage.js:312 getting row data
16:56:32.485 CsetComparisonPage.js:312 getting row data
16:56:32.490 react-dom.production.min.js:189 NotFoundGraphError: Graph.addEdge: source node "40828939" not found.
    at Pe (graph.js:218:11)
    at forEach.forEach.e.generateKey.Ie.<computed> [as addEdge] (graph.js:2954:16)
    at CsetComparisonPage.js:320:25
    at Array.forEach (<anonymous>)
    at W.concepts (CsetComparisonPage.js:320:9)
    at nG (CsetComparisonPage.js:141:56)
    at Sa (react-dom.production.min.js:167:137)
    at Ou (react-dom.production.min.js:197:258)
    at kc (react-dom.production.min.js:292:88)
    at bs (react-dom.production.min.js:280:389)
du @ react-dom.production.min.js:189
16:56:32.491 react-dom.production.min.js:283 Uncaught NotFoundGraphError: Graph.addEdge: source node "40828939" not found.
    at Pe (graph.js:218:11)
    at forEach.forEach.e.generateKey.Ie.<computed> [as addEdge] (graph.js:2954:16)
    at CsetComparisonPage.js:320:25
    at Array.forEach (<anonymous>)
    at W.concepts (CsetComparisonPage.js:320:9)
    at nG (CsetComparisonPage.js:141:56)
    at Sa (react-dom.production.min.js:167:137)
    at Ou (react-dom.production.min.js:197:258)
    at kc (react-dom.production.min.js:292:88)
    at bs (react-dom.production.min.js:280:389)
16:56:44.625 DataCache.js:96 compressed cache just grew by 104.49% to 2,425,153 chars
16:58:32.489 cset-comparison:1 Uncaught (in promise) Error: A listener indicated an asynchronous response by returning true, but the message channel closed before a response was received
```

</p>
</details> 

## Additional information
I observed no errors in the backend logs.

Strangely, I tried to replicate this a second time but was not able to. The comparison page loaded successfully. I followed the following workflow: Clear cache, load from the URL, click "cset comparison". Load http://bit.ly/termhub-dev, select csets manually, click "cset comparison".

**Comment by joeflack4** [comment]
Since I couldn't replicate, and if the frontend logs are not helpful, maybe you can close.

**Comment by Sigfried** [comment]
Not sure how to work on this without a replication recipe.

**Comment by joeflack4** [comment]
@Sigfried The replication recipe so to speak I did not do in bulleted form this time. It's:
### First variation
1. Go to: https://icy-ground-0416a040f.2.azurestaticapps.net/OMOPConceptSets?codeset_ids=417730759&codeset_ids=423850600&codeset_ids=966671711&codeset_ids=577774492
2. After loading csets using the URL above, click "cset comparison"

### Second variation
1. Start at the "cset search" page. Select all the concepts with code id's in above URL
2. After loading csets using the URL above, click "cset comparison"

**Comment by joeflack4** [comment]
Now is covered by #514
