### ISSUE TITLE
Bug: Unable to load certain edge case csets

### ISSUE THREAD

**Issue by joeflack4** [jhu-bids/TermHub#511]
## Overview
Unable to load certain edge case csets.

## Replicability
1. Load [TermHub dev](https://icy-ground-0416a040f.2.azurestaticapps.net/)
2.a.1 Go to the Help/About page
2.a.2. In "Load a set of concept sets", enter "1", and then click the link that appears: https://icy-ground-0416a040f.2.azurestaticapps.net/OMOPConceptSets?codeset_ids=1
OR
2.b.1. Go to the normal cset search page
2.b.2 Select the first concept set "1 [TermHub Test] [Simplified autoimmune disease] GI: Celiac Disease (v1) (Empty)"
2.b.3. Click "Load concept sets"
3. Observe blank screen & errors in console (see "additional information")

## Possible causes
a. The concept set selected doesn't have any members
b. The concept set has an 'invalid' or short concept ID, e.g. "1"

## Additional information
**Low priority**: Seems like a super low priority because I think it's going to be rare that this happens, and only to csets that nobody cares about (e.g. these empty test csets).

<details><summary>Stacktrace</summary>
<p>

```
509:00:10.562 Refused to load the font '<URL>' because it violates the following Content Security Policy directive: "default-src https: 'unsafe-eval' 'unsafe-inline'". Note that 'font-src' was not explicitly set, so 'default-src' is used as a fallback.

09:00:13.855 react-dom.production.min.js:189 TypeError: Cannot convert undefined or null to object
    at Function.entries (<anonymous>)
    at WW (ConceptSetCard.js:156:18)
    at Sa (react-dom.production.min.js:167:137)
    at kc (react-dom.production.min.js:290:337)
    at bs (react-dom.production.min.js:280:389)
    at ms (react-dom.production.min.js:280:320)
    at gs (react-dom.production.min.js:280:180)
    at is (react-dom.production.min.js:271:88)
    at os (react-dom.production.min.js:268:429)
    at _ (scheduler.production.min.js:13:203)
overrideMethod @ console.js:213
du @ react-dom.production.min.js:189
n.callback @ react-dom.production.min.js:189
zi @ react-dom.production.min.js:144
wc @ react-dom.production.min.js:262
bc @ react-dom.production.min.js:260
yc @ react-dom.production.min.js:259
(anonymous) @ react-dom.production.min.js:283
xs @ react-dom.production.min.js:281
os @ react-dom.production.min.js:270
_ @ scheduler.production.min.js:13
M @ scheduler.production.min.js:14
Show 1 more frame
Show less
09:00:13.856 ConceptSetCard.js:156 Uncaught TypeError: Cannot convert undefined or null to object
    at Function.entries (<anonymous>)
    at WW (ConceptSetCard.js:156:18)
    at Sa (react-dom.production.min.js:167:137)
    at kc (react-dom.production.min.js:290:337)
    at bs (react-dom.production.min.js:280:389)
    at ms (react-dom.production.min.js:280:320)
    at gs (react-dom.production.min.js:280:180)
    at is (react-dom.production.min.js:271:88)
    at os (react-dom.production.min.js:268:429)
    at _ (scheduler.production.min.js:13:203)
WW @ ConceptSetCard.js:156
Sa @ react-dom.production.min.js:167
kc @ react-dom.production.min.js:290
bs @ react-dom.production.min.js:280
ms @ react-dom.production.min.js:280
gs @ react-dom.production.min.js:280
is @ react-dom.production.min.js:271
os @ react-dom.production.min.js:268
_ @ scheduler.production.min.js:13
M @ scheduler.production.min.js:14
09:01:03.565 OMOPConceptSets:1 Uncaught (in promise) Error: A listener indicated an asynchronous response by returning true, but the message channel closed before a response was received
```

</p>
</details>

**Comment by joeflack4** [comment]
@hlehmann17 You encountered this, but I don't think this is a major concern. I think this only happens for these empty test case csets I created.

**Comment by joeflack4** [comment]
@Sigfried Looks like this got fixed at some point! I see that it is successfully loading (screenshots below), so I'm closing this.

<img width="1240" alt="Screenshot 2024-04-13 at 7 12 55 PM" src="https://github.com/jhu-bids/TermHub/assets/13045020/d656e3f1-6046-4995-90ce-4b43ce3cbee6">

<img width="1709" alt="Screenshot 2024-04-13 at 7 13 01 PM" src="https://github.com/jhu-bids/TermHub/assets/13045020/7af1ad90-d1a3-4be3-a70d-618af9dc41f0">
